### ISSUE TITLE
Example functions return #N/Ain Web

### ISSUE THREAD

**Issue by CristovaoTorres** [OfficeDev/Excel-Custom-Functions#257]
*** This repo is for issues related to the current Excel Custom Functions sample. ***

If you have an issue _running_ your custom function, please log an issue in the official office-js repo here: [https://github.com/OfficeDev/office-js/issues](https://github.com/OfficeDev/office-js/issues) ***

I'm having trouble with the custom function.

only on the web I always have the return # N / A

yesterday it worked perfectly

![image](https://user-images.githubusercontent.com/46796748/108741123-262a4700-7515-11eb-8a88-9dd36eacd443.png)

**Comment by TCourtneyOwen** [comment]
@CristovaoTorres Can you please try the following:

- Find "https://localhost:3000/dist/functions.html" in the project manifest.xml file
- Remove the "dist" portion from the functions.html such that it looks like this: https://localhost:3000/functions.html
- Rebuild and restart your custom functions project

I think this should fix the problem, but please let us know if it doesn't.

Thanks,

Courtney

**Comment by CristovaoTorres** [comment]
Thanks.

I changed the file but the problem still remains.
![image](https://user-images.githubusercontent.com/46796748/108742628-a4d3b400-7516-11eb-8814-496ec8b09d4b.png)

**Comment by TCourtneyOwen** [comment]
OK, then this might be a different issue. Let me dig into this a bit more because I am also seeing the same behavior you are reporting.  I will get back to you.

Thanks,

Courtney

**Comment by CristovaoTorres** [comment]
Ok
Remembering that yesterday it worked perfectly and for some reason today, it stopped working.

**Comment by TCourtneyOwen** [comment]
Yes, that is good to know, as I had this working last week when I tried it. I likely will end up reporting this issue to the Custom Functions team if I can't find a quick solution.

**Comment by TCourtneyOwen** [comment]
I also get some very bizarre behavior that it ends up filling in a bunch of cells as follows when it tries to resolve the function (e.g. = contoso.add(1,2):

![image](https://user-images.githubusercontent.com/38081557/108745454-f3ba2300-74ef-11eb-9740-cd74fe2a059c.png)

**Comment by CristovaoTorres** [comment]
I think the problem is some update in excel. =/

**Comment by TCourtneyOwen** [comment]
I think this may be a problem with Excel Online and not unique to custom functions. Even entering a built-in Excel function such as =SUM(1,2) fails. Some serious issues appear to be going on with Excel Online at the moment

**Comment by TCourtneyOwen** [comment]
Yes, you beat me to it - something with Excel Online

**Comment by CristovaoTorres** [comment]
No problems for me.
![image](https://user-images.githubusercontent.com/46796748/108746132-aef7b180-751a-11eb-8245-494365f266b7.png)

**Comment by TCourtneyOwen** [comment]
I just looped in some of the Custom Functions people on this issue. I will let you know what I hear. They may chime in on this thread too.

**Comment by xiaochunms** [comment]
@CristovaoTorres Sorry for the issue. May you please help to share your Excel version information? Furthermore, is it possible to share your project which used to work that I can debug at my side?

**Comment by raflyalk** [comment]
Hi, I'm also having the same problem with Excel Custom Function on Excel for Web. I also tried test making a custom function using  Script Lab but also results in #N/A error as well. But the problem doesn't exist on Excel Desktop. So I think the problem is from the Excel for Web.

**Comment by CristovaoTorres** [comment]
> @CristovaoTorres Desculpe pelo problema. Você pode ajudar a compartilhar suas informações de versão do Excel? Além disso, é possível compartilhar seu projeto que funcionava para que eu possa depurar ao meu lado?

**Comment by CristovaoTorres** [comment]
> @CristovaoTorres Desculpe pelo problema. Você pode ajudar a compartilhar suas informações de versão do Excel? Além disso, é possível compartilhar seu projeto que funcionava para que eu possa depurar ao meu lado?

I am using the template project following this.
https://docs.microsoft.com/pt-br/office/dev/add-ins/quickstarts/excel-quickstart-jquery?tabs=yeomangenerator

Excel Custo Function
TypeScript

**Comment by CristovaoTorres** [comment]
Closed without intention

**Comment by CristovaoTorres** [comment]
> > @CristovaoTorres Desculpe pelo problema. Você pode ajudar a compartilhar suas informações de versão do Excel? Além disso, é possível compartilhar seu projeto que funcionava para que eu possa depurar ao meu lado?
> 
> I am using the template project following this.
> https://docs.microsoft.com/pt-br/office/dev/add-ins/quickstarts/excel-quickstart-jquery?tabs=yeomangenerator
> 
> Excel Custo Function
> TypeScript

Follow the project

https://github.com/CristovaoTorres/ExcelCustomFunction

**Comment by raflyalk** [comment]
I tried using the custom function on Excel for Web today and the problem has been fixed. You can try again @CristovaoTorres .

**Comment by TCourtneyOwen** [comment]
Wow, that's surprising - it works for me now too! 

@xiaochunms did you make a fix for the issue? If not, then maybe the issue was indeed with XLO and not custom functions

**Comment by xiaochunms** [comment]
@raflyalk thanks for the check. @TCourtneyOwen the issue is in add-in part, but it impacts custom functions. Just reverting the change fixes the issue then.

**Comment by CristovaoTorres** [comment]
> I tried using the custom function on Excel for Web today and the problem has been fixed. You can try again @CristovaoTorres .

It works for me too.,
Tks  =D
